/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F0308.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void){
	for (uint32_t i = 0; i < 500000; i++)
	{

	}
}

int main(void)
{
	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_Handle_t GpioLedPC8;
	GPIO_Handle_t GpioLedPC9;
	GPIO_Handle_t GpioButtPA0;

	GpioLedPC8.pGPIOx = GPIOC;
	GpioLedPC8.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_8;
	GpioLedPC8.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLedPC8.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLedPC8.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLedPC8.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&GpioLedPC8);

	GpioLedPC9.pGPIOx = GPIOC;
	GpioLedPC9.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9;
	GpioLedPC9.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLedPC9.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLedPC9.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLedPC9.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&GpioLedPC9);

	GpioButtPA0.pGPIOx = GPIOA;
	GpioButtPA0.GPIO_PinConfig.GPIO_PinNumber - GPIO_PIN_NO_0;
	GpioButtPA0.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GpioButtPA0.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioButtPA0.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&GpioButtPA0);

	GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_NO_8, SET);
	while(1){
		if (GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0)){
			GPIO_TogglePin(GPIOC, GPIO_PIN_NO_8);
			GPIO_TogglePin(GPIOC, GPIO_PIN_NO_9);
			delay();
		}
	}
    return 0;
}
